### PR TITLE
Fixes for hosts that are not spacedock.info

### PR DESCRIPTION
**Pull request by HebaruSan**
## Background / progress update

As of #198, the `master` branch now has identical code to the production server.

The dev servers are live-ish and are switched to their individual branches:

| Server | Branch |
| --- | --- |
| https://alpha.spacedock.info/ | https://github.com/KSP-SpaceDock/SpaceDock/tree/alpha |
| https://beta.spacedock.info/ | https://github.com/KSP-SpaceDock/SpaceDock/tree/beta |

## Problems

The `redirect()` calls are hard coded to `spacedock.info`, which prevents them from working on other servers. We need to fix that for the dev servers to work.

There is code to pull changes from GitHub and restart the server when GitHub notifies us of a change. But while it validates the notification against a configurable branch, it still only pulls from `master`, which won't work for the dev servers. They should be pulling from their specific branches, so each server can test the changes that are intended for it.

## Changes

Now the hard coding of `spacedock.info` is removed from `redirect()` calls. The original problem that this was done to work around is already solved by configuring the reverse proxy server to send the original `Host` header to the app server:

- https://docs.trafficserver.apache.org/en/7.1.x/admin-guide/files/records.config.en.html#proxy-config-url-remap-pristine-host-hdr

Now the `hook_branch` setting is used for the pull command.

## Process (as I understand it)

This pull request is targeting the `alpha` branch. If it is merged, I will log in to the alpha server and pull the alpha branch and restart it manually. Then we will test.

After we confirm that it works, another pull request will migrate these changes to the `beta` branch, whereupon testing will commence on the beta server via the same steps.

Finally, a third pull request will move these changes to `master`, and @V1TA5 will deploy them to production.

Once these changes are present on the servers, we can try setting up GitHub to notify them to pull and restart when their branches change. Thereafter the dev process should be able to operate solely through pull requests, without manually logging in and pulling changes and restarting.

### CODE REVIEW

**Comment by V1TA5** [comment]
Exactly.
alpha is always bleeding edge and unstable. It includes stuff we want to include in future releases but there are still known bugs (or bugs devs can easily identify themselves).

Beta is a staging area where we CAN invite the public to find bugs. Beta also never adds any new features but only fixes bugs not known in alpha (a feature freeze in alpha might be needed before moving code from alpha to beta so that known bugs can be fixed).

Gamma aka production will be updated if we agree that a beta version doesnt introduce new bugs and brings benefits over the current production version. (Hotfixes net special rules that are yet to be determined). deployment of new versions on production wont be instant but follow maintanance windows and prior announcements both on the forums and if possible on the site.
(a setup where two gamma servers exists and one is used to set up a new version using the same db instance and a switchover between them when its working like expected is desirable).

at least thats the plan as of now. Reality may comment on that :)

**Comment by HebaruSan** [comment]
OK, this is now live on the alpha server.

**Comment by V1TA5** [comment]
You are the man!

**Comment by HebaruSan** [comment]
Merging #203 triggered this in `/var/log/apache2/spacedock.info-access.log` on the alpha server:

```
10.150.1.9 - - [22/Jul/2019:19:28:42 +0000] "POST /hook/ HTTP/1.1" 404 195094 "-" "GitHub-Hookshot/396ac6e"
```

However, no pull or restart appears to have happened. Likely permissions problems, since I have to `sudo` to pull, but the code doesn't do that. A `chown` may be in order.

**Pull request merged**
