### PR TITLE
Enhancement/newbrand

### PR DESCRIPTION
**Pull request by sharksharkco**
New colors/logos/icons

### CODE REVIEW

**Comment by FrikFry** [comment]
Can you remove these files from the static dir?

```
static/SpaceDock-Icon-Text-Transparent.svg
static/SpaceDock-Icon-Text-Transparent@2x.png
static/index.
static/stylesheet.css
```

**Comment by sharksharkco** [comment]
All set

**Comment by FrikFry** [comment]
LGTM :+1:

**Comment by sharksharkco** [comment]
Merge away

**Pull request merged**
