### PR TITLE
Add type hints

### PR DESCRIPTION
**Pull request by HebaruSan**
## Motivation

Type hints allow us to specify how a function is supposed to be used and catch when it isn't. They're especially helpful when writing new code, as trivial errors such as trying to access `my_dict['prop']` as `my_dict.prop` (my personal bugbear) are caught before run-time, but are also useful if you just need to know what a function returns or what to pass to it. They're a standard part of Python:

- https://www.python.org/dev/peps/pep-0484/

The `mypy` utility uses type hints to perform type checking:

- http://mypy-lang.org/

## Changes

- A `mypy.ini` file is added to the project root with some convenient defaults
- `.mypy_cache` is now git-ignored
- Type hints are added everywhere

```
$ mypy KerbalStuff 
Success: no issues found in 25 source files
```

### Possibly functional changes

The process of adding type hints revealed a few problems and opportunities for improvement.

- Unreachable code fixed; CKAN triggers weren't being sent after mod authors marked a mod compatible with the latest game version:
  https://github.com/KSP-SpaceDock/SpaceDock/blob/e91894465c3a2885531355b9c813493ad93eaca4/KerbalStuff/blueprints/mods.py#L506-L507
- Removed handling of non-existent `templates/mobile` directory:
  https://github.com/KSP-SpaceDock/SpaceDock/tree/alpha/templates
  https://github.com/KSP-SpaceDock/SpaceDock/blob/b7cb750b5b71e497f5d791c1754e55c1ac90ed0c/KerbalStuff/app.py#L203-L207
- Cleaned up GitHUB OAuth helper function that could return redirects and strings, but was used as if it would never do that:
  https://github.com/KSP-SpaceDock/SpaceDock/blob/b7cb750b5b71e497f5d791c1754e55c1ac90ed0c/KerbalStuff/blueprints/login_oauth.py#L61-L72
  https://github.com/KSP-SpaceDock/SpaceDock/blob/b7cb750b5b71e497f5d791c1754e55c1ac90ed0c/KerbalStuff/blueprints/login_oauth.py#L134
  https://github.com/KSP-SpaceDock/SpaceDock/blob/b7cb750b5b71e497f5d791c1754e55c1ac90ed0c/KerbalStuff/blueprints/login_oauth.py#L161

Otherwise everything should work the same as before.

### CODE REVIEW

**Comment by RockyTV** [comment]
Not that it matters much but is there a reason to choose `mypy` over `pylint` or other linter widely used by the Python community?

Also, I think type hinting only works with a linter, meaning someone can skip the linting process before committing a change and it could lead to the same situation we are right now without the type hints. We could include type checking in the methods to make sure we're receiving what we expect, instead of just doing it in "compile" time.

Makes me think if a linting pre-commit hook is necessary.

**Comment by HebaruSan** [comment]
> Not that it matters much but is there a reason to choose `mypy` over `pylint` or other linter widely used by the Python community?

Currently, `mypy` hasn't been "chosen" in any sense that matters, other than providing a default config for it. It's just one tool that supports Python's standard type hinting syntax (this syntax is **not** specific to `mypy`). But...

> Also, I think type hinting only works with a linter, meaning someone can skip the linting process before committing a change and it could lead to the same situation we are right now without the type hints.
> 
> Makes me think if a linting pre-commit hook is necessary.

Good idea, I'll look into this and update with something (which will likely make `mypy` "chosen" in a more meaningful way). @DasSkelett knows a lot about GitHub Actions, maybe he can figure something out quickly.

> We could include type checking in the methods to make sure we're receiving what we expect, instead of just doing it in "compile" time.

If you want to take this on, please feel free. I'm focusing on type hints for static type checking in this pull request.

**Comment by RockyTV** [comment]
The hook part is easy, I think we just need to add a file at `.git/hooks`. We could use GH Actions to run the linter so we can check for issues whenever we submit a PR.

**Comment by HebaruSan** [comment]
OK, that latest commit is what we need as far as I can tell. Doesn't look like it ran though. I guess it has to get to master first?

**Comment by DasSkelett** [comment]
The new commit was a step in the right direction, but I think the PR source branch has to be a branch of the target repository for new workflows to run.
I.e. if you push your local branch to a new branch in the `SpaceDock` repository instead of yours (`HebaruSan`), it should work.

I think it'd a safety mechanism so no one can create a PR with a new bad workflow file and somehow leake secrets or screw you over otherwise.

**Comment by HebaruSan** [comment]
OK, will switch over to a branch in the main repo, brace for imminent replacement of PR...

**Comment by HebaruSan** [comment]
Replaced by #270.

**Pull request closed without merging**
