### PR TITLE
Let users choose which emails to receive

### LINKED ISSUE #333: new Upvote button, ignore auto-updated followed mods
I use follow almost like "upvote", because there is no other spacedock-related free way to compliment mod author, and ofthen I don't really need the email messaging feature.
 
Also, the email messaging, then author just clicked *yes, my mod compatible for a new version of ksp* is not so helpful, so I propose :
* *  **Upvote** (or **Like**) button, next to the **Follow** button, and a number of likes on mod's page
  * **Mods \<username\> upvoted** (or **Mods \<username\> likes**) block on the user page, after the **Mods \<username\> follows**
* ignore email messaging for mods, that is updated by the *yes, update automatically* button or make а checkbox for that somewhere.

### PR DESCRIPTION
**Pull request by HebaruSan**
## Motivation

Currently if you follow a mod, you receive all email notifications for it. Some users might not want to receive notifications for compatibility updates.

## Changes

Fixes #333 (the part about ignoring the auto-update email).

### UI

Now if you edit your profile, a new section lists the mods you follow, with two checkboxes for each. The rows are striped to make it easier to pick out the associations between the contents of each row:

image

If you uncheck a checkbox (and save your changes), you won't receive that notification for that mod anymore. Each column of checkboxes has "Check all" and "Uncheck all" buttons that check and uncheck all the checkboxes in that column, so users can easily disable all notifications of a particular type.

Admins are allowed to edit these settings for other users in case someone requests it and can't figure out how to do it.

### Data model

To make this possible, the `mod_followers` table has two new bool columns, both set to True for all old rows:

- `send_update` - True to send regular update notifications, False to suppress them
- `send_autoupdate` - True to send auto-update notifications, False to suppress them

In addition, `mod_followers` now has three new indices:

- `mod_id` to make it faster to find all of the followers of a mod
- `user_id` to make it faster to find all the mods a user follows
- `(user_id, mod_id)` to make it faster to find a particular user's follow row for a particular mod

### Side fixes

The user description field in the profile edit screen now uses the rich text editor; the field has always supported markdown, but the rich text editor wasn't enabled before.

### CODE REVIEW

**Comment by HebaruSan** [comment]
(Planning to wait to rebase until after #350 is merged, so we don't have to rebase multiple times.)

**Comment by DasSkelett** [comment]
Hm, I think when rebasing after #350 you didn't actually rebase on alpha after it was merged, but right after #373.
The `down_revision` is also pointing to #370.

**Comment by HebaruSan** [comment]
Ahh right, I probably forgot to check out and pull alpha. Should be OK now?

**Comment by DasSkelett** [comment]
The migration and code in `objects.py` don't match currently, and there are also issues with the relationsships between `User`<->`Following`<->`Mod`.
Attempting a fix here: https://github.com/HebaruSan/SpaceDock/pull/3

**Comment by HebaruSan** [comment]
> The migration and code in `objects.py` don't match currently, and there are also issues with the relationsships between `User`<->`Following`<->`Mod`.

How does this look after merging your fixes?

**Comment by DasSkelett** [comment]
> How does this look after merging your fixes?

We should be fine now, alembic generates empty revisions. The indexes are used as well, after filling the tables with some data, so I'm confident they're used on production as well.

**Comment by DasSkelett** [comment]
We should also specify some `col-xs-*` classes for the email settings container, with the "default" layout it's hard to recognize which "Check all" / "Uncheck all" buttons toggle which option on smartphones:
<details>
<summary>Screenshot</summary>

image
</details>

I've managed to split them into two columns again, so it's easier to understand which buttons are for which option.

<details>
<summary>Screenshot</summary>

image
</details>

Do you like this layout? If so, I  can push a commit. It's not much, just adding `col-xs-12` to the columns with `col-md-3`, and `col-xs-6` to `col-md-2`.

**Comment by HebaruSan** [comment]
> Do you like this layout?

Yes, that looks a lot better, thanks!

**Comment by DasSkelett** [comment]
One more small bug I just found in testing, in the auto-update email subject we take the game version of `mod.versions[0]`, while it's `mod.default_version` that is being updated. usually it's the same, but not necessarily.
In the email body the correct one is used already.
Fixed in the latest commit.

**Review by DasSkelett — APPROVED** [review]
Looks solid to me. If you want, you can squash before merge.

**Comment by HebaruSan** [comment]
Took me a while to figure out how to run migrations on alpha. For future reference, this seemed to work:

```
cd /SpaceDock
bin/alembic upgrade 17fbd4ff8193
```

**Comment by DasSkelett** [comment]
Sorry, forgot about it this time. `alembic upgrade head` works as well.

**Comment by HebaruSan** [comment]
No problem, it's something I should learn anyway. I'll try to remember the `head` alias is available.

**Pull request merged**
