### PR TITLE
Allow getting unpublished mods via API

### PR DESCRIPTION
**Pull request by ihsoft**
If mod is unpublished, it's still hidden from anyone, except the owner.

### CODE REVIEW

**Comment by V1TA5** [comment]
So it currently allows anyone to see unpublished mods via the api? 

We once had Test systems for that. I could provide some Linux boxes to test fixes if youre willing to help with the code on a regular basis.

**Comment by ihsoft** [comment]
> So it currently allows anyone to see unpublished mods via the api?

Not anyone. Only the owner of the mod will be able to see the unpublished mod, given the call is authorized. The unauthorized calls will be rejected with 401.

> I could provide some Linux boxes to test fixes if youre willing to help with the code on a regular basis.

Not sure I can commit on the "regular basis" term. Is there a scope of work and deadlines? Any obligations under this term?

**Comment by RockyTV** [comment]
I don't see what's wrong? If the mod is not published, why would anyone be able to see it? This is what `unpublished` means. It should be visible to the owner only.

**Comment by V1TA5** [comment]
No Deadlines.
Theres little work done on the code. Thomas and RockyTV are the people to talk to. 
I simply dont have the time to code.

**Comment by StollD** [comment]
The only fear I have is that (if I recall this correctly) the production instance has various uncommitted (hot)fixes, and noone knows what exactly was changed anymore.

We should probably figure that out before deploying this.

**Comment by V1TA5** [comment]
Yes. I did some stuff to it.
I can put the prod code somewhere so you or someone else could compare it.

**Comment by StollD** [comment]
Assuming the code in prod is simply the cloned git repository, you could just do something like this:

```
git checkout -b hotfixes
git add -A
git commit -m "Changes to compare"
git push
```

Then we would simply have the current prod code in its own branch.

**Pull request merged**
