### PR TITLE
Fix bcrypt bug in 2.0

### PR DESCRIPTION
**Pull request by FrikFry**

### CODE REVIEW

**Comment by ThomasKerman** [comment]
While the first change was required for me to build and run bcrypt, the second was not. Note, that I was using docker-compose, with the bare dockerfile, it seemed to install bcrypt 1.1, which needs the second change.

I already had that problem some hours ago, but @godarklight and me could verify that I was running 1.1, so that I didn't committed that change.

**Comment by FrikFry** [comment]
Well, I can confirm that this was required with bcrypt 2.0 for me locally. Perhaps there was a strange caching issue going on on the server.

**Comment by FrikFry** [comment]
@ThomasKerman Well I was able to build Dockerfile with the first change as well, but having the encode/decode lines is breaking for me on register/logging, so it looks like both changes are required with bcrypt 2.

**Comment by godarklight** [comment]
*hiss* :P

**Pull request closed without merging**
