### PR TITLE
Add file size to version download button

### PR DESCRIPTION
**Pull request by RockyTV**

### CODE REVIEW

**Comment by godarklight** [comment]
This looks mostly fine, but wouldn't it be better sending a dictionary of file sizes rather than doing 2 foreach's and only printing when they match?

**Comment by RockyTV** [comment]
@godarklight that's what the change does, I think. What is your suggestion?

**Comment by RockyTV** [comment]
Excuse me, why was this closed?

**Comment by godarklight** [comment]
Actually not sure, unless it's a merge conflict - we'll fix it up :P

**Comment by RockyTV** [comment]
Yeah, should be it. I haven't updated it since VITAS started with the new
design.

**Comment by TN-1** [comment]
I closed it because it seemed to be abandoned. Ill reopen.

**Comment by RockyTV** [comment]
Merge conflicts were fixed.

**Comment by HebaruSan** [comment]
Apologies for the automated close, the `dev` branch is being replaced a new set of branches. I'll try to re-open this when that's all set up.

**Pull request closed without merging**
