### PR TITLE
Docker Compose

### PR DESCRIPTION
**Pull request by FrikFry**
@absoutherland Here is where I was going with my attempts at docker-compose. Don't much care for how the DB initialization is done though at the moment. There seems like there should be a cleaner way.

### CODE REVIEW

**Comment by FrikFry** [comment]
This mostly works now. Open questions are if we like the mail changes I did and if we like how the db is initialized.

**Comment by FrikFry** [comment]
@ThomasKerman @GenPage Any problems with merging this?

**Comment by GenPage** [comment]
LGTM :+1:

**Comment by ThomasKerman** [comment]
Closing this, merging it manually into dev

**Pull request closed without merging**
