### PR TITLE
Implement caching

### PR DESCRIPTION
**Pull request by HebaruSan**
@godarklight created this branch to speed up various page loads by caching some calculations.

I wasn't following the chat in extreme depth, but I believe it applies some sort of caching to the code that searches over all mods and calculates their scores.

### CODE REVIEW

**Comment by HebaruSan** [comment]
This probably ought to be heavily refactored, we don't need dozens of places that implement their own calls to `time.time()` individually and then manipulate a caching data structure.

Not sure if we should write a `Cache` class or if just putting some shared variables and functions in a `cache.py` would be better.

**Comment by HebaruSan** [comment]
Is there a module for this? Why yes, there might be:

- https://flask-caching.readthedocs.io/en/latest/

Looks pretty applicable so far...

**Comment by godarklight** [comment]
This can only be tested when the database is filled with a lot of garbage. In my local testing 10,000 mods results in get_mods taking 20 seconds to complete.  
  
login.sh
```
curl -F username=godarklight -F password=PASSWORDHERE -c ./cookies "http://127.0.0.1:8080/api/login"
```

create.sh
```
#!/bin/bash
for i in {1..10000}; do
curl -b ./cookies \
    -F "name=Test mod $i" \
    -F "short-description=Short Description $i" \
    -F "version=1.0.$i" \
    -F "game-id=1" \
    -F "game-version=v1.9.1" \
    -F "license=MIT" \
    -F "zipball=@test.zip" \
    -F "ckan=false" \
    "http://127.0.0.1:8080/api/mod/create"
done
```

edit.sh
```
#!/bin/bash
for i in {1..10010}; do
curl -b ./cookies \
-F "background=" \
-F "bg-offset-y=" \
-F "short-description=Short Description $i" \
-F "license=MIT" \
-F "donation-link=" \
-F "external-link=" \
-F "source-link=" \
-F "description=Description $i" \
"http://127.0.0.1:8080/mod/$i/blah/edit"
done
```

publish.sh
```
#!/bin/bash
for i in {1..10010}; do
curl -b ./cookies "http://127.0.0.1:8080/mod/$i/blah/publish"
done
```

**Comment by HebaruSan** [comment]
image

**Pull request closed without merging**
