### PR TITLE
Add Game.ckan_enabled to remove hardcoded game id checks

### LINKED ISSUE #329: Turn the ksp-game-id var into db flags
Please turn the ksp-game-id var into db flags.
The code should be as game independent as possible. We don't want to crowd config.ini with game specific flags if possible.
(CKAN specific ones could be columns in the db table. Could also come in handy if they/you ever support other games too)

_Originally posted by @V1TA5 in https://github.com/KSP-SpaceDock/SpaceDock/pull/294#issuecomment-704061030_

### PR DESCRIPTION
**Pull request by DasSkelett**
## Problem
We have hardcoded game id checks in the CoffeeScript code that show the "Add to CKAN" checkboxes based on the `id` of KSP in the production database.

This is neither good practice nor future proof if there ever comes a new game that will be supported by CKAN and SpaceDock (looking at KSP 2).

## Solution
There's a new boolean column for the `Game` table, `ckan_enabled`. The alembic script is set up for production, it sets `ckan_enabled` to `True` for the game with the id `3102`, which is KSP.

The mentioned frontend code is removed, instead we use Jinja2 `if`s to decide whether to render the checkboxes or not.

We also check `ckan_enabled` in `edit_mod()` and `create_mod()` before setting it to `True`.

It's also checked in `send_to_ckan()` and `notify_ckan()`.

Whenever this commit is merged to a new branch, we need to execute `source bin/activate; alembic upgrade head` on the corresponding server.

### `ksp-game-id`

In #294 we added the ability to import game versions from CKAN's repo. This was done by creating a `ksp-game-id` setting in `config.ini` that tells us which `Game` row is KSP. Now that we have a separate flag for CKAN enablement, we use that instead.

Fixes #329.

### CODE REVIEW

**Comment by HebaruSan** [comment]
I'm sure that the reason this hack was left in place for so long was that folks wanted a special table of external integration hooks rather than just a bool in Game, so e.g. Factorio could trigger [CFAN](https://forums.factorio.com/viewtopic.php?t=23109), etc. Would that be difficult to start?

**Comment by DasSkelett** [comment]
Writing along my thoughts how to implement this:

1) New `modmanager` table:
    `ModManager.name`, `ModManager.games` <-> `Game.mod_managers` (many-to-many relationship, this will be fun), `ModManager.notify_function`, `ModManager.send_to_function`
2) General `send_mod_to_manager()` and `notify_manager()`, doing something like this: 
    ```
    for mm in mod.game.mod_managers:
		if mm in mod.enabled_mod_managers:
		    getattr(self, mm.send_to_function)()
    ```
3) Change `{% if ga.ckan_enabled %}` to `{% if 'CKAN' in mod_managers %}` in the templates, and passing `mod_managers=mod.game.mod_managers.with_entities(ModManager.name).all()` to them.
    Alternatively, create a `for` loop and pull all needed data from the db.
4) Similarly, change all new `Game.ckan_enabled` checks to `'CKAN' in mod.game.mod_managers.with_entities(ModManager.name).all()` in the backend code
5) Change bool `Mod.ckan` to list `Mod.enabled_mod_managers`, and
    Change `mod.ckan` checks to `'CKAN' in mod.enabled_mod_managers`

So indeed a bunch of work. But if you think there's a worthy chance that we want to support another mod manager / external service to notify in the not too distant future, it should be doable.

**Comment by HebaruSan** [comment]
> But if you think there's a worthy chance that we want to support another mod manager / external service to notify in the not too distant future

My crystal ball is out of order. :crystal_ball:

In general I like where you're going with those thoughts. It might be even more complicated though.

- Would all mod managers accept the same JSON input format for these hooks? We pretty freely change them today with only CKAN in the mix.
- Would other mod managers want more/different hooks?

Seems like there would be a lot of complications that could only be tackled at the point where we were implementing support for the "next" mod manager, whatever it happened to be.

What about a partial solution? Maybe we can make the current structure _slightly_ more generic, and simply leave the door open as cleanly as possible to future work.

**Comment by RockyTV** [comment]
We could have a generic code in place, and CKAN/CFAN use the same syntax. Then we could decide the format or if we want to support other mod managers.

> 3. Change `{% if ga.ckan_enabled %}` to `{% if 'CKAN' in mod_managers %}` in the templates, and passing `mod_managers=mod.game.mod_managers.with_entities(ModManager.name).all()` to them.

I'd suggest rename `ckan_enabled` to `mod_manager_enabled` or something like that and have it refer to the respective entry in the `ModManagers` table.

**Comment by DasSkelett** [comment]
> What about a partial solution? Maybe we can make the current structure _slightly_ more generic, and simply leave the door open as cleanly as possible to future work.

Hmm, don't have an idea of a good middle ground yet, but maybe something comes up.

>     * Would all mod managers accept the same JSON input format for these hooks? We pretty freely change them today with only CKAN in the mix.

This would be part of the manager-specific functions, so we should be able to have the POST parameters adjusted to each mod manager.

> I'd suggest rename `ckan_enabled` to `mod_manager_enabled` or something like that and have it refer to the respective entry in the `ModManagers` table.

This would eliminate the possibility of multiple mod managers per game, which I thought would be good to have.

**Comment by HebaruSan** [comment]
Rebased on alpha because this could be helpful for #329. Mypy fixes incoming shortly...

**Comment by HebaruSan** [comment]
@godarklight's validation check catches alembic migration issues! :tada:

**Comment by HebaruSan** [comment]
Added a fix for #329. I would not say this is necessarily the stopping point for these changes, but it's at least a placeholder for when we move towards a `ModManager`-like solution.

**Comment by HebaruSan** [comment]
Ooh, for the message formatting, we could store template strings in the records (editable in the admin UI), then populate them with jinja2!

```
{
    "name": "{{mod.name}}",
    "id": "{{mod.id}}",
   etc...
}
```

**Comment by HebaruSan** [comment]
Replaced by #480.

**Pull request closed without merging**
