### PR TITLE
User profile fields for KerbalX and GitHub

### PR DESCRIPTION
**Pull request by HebaruSan**
## Motivation

The profile currently allows the user to enter their username on the KSP forum, Twitter, Reddit, and IRC. I think GitHub is more important for modders, and KerbalX is more important for a lot of non-modders.

## Changes

Now the profile has KerbalX and GitHub fields.
Note that this will need to be rebased if #380 is merged first, or vice versa, since both have migrations with the same down revision.

### CODE REVIEW

**Comment by DasSkelett** [comment]
I think it's time to differentiate between fields where only the username is required (Twitter, Reddit, GitHub, KerbalX), and where the complete link is required (KSP Forums), on the edit page. I've seen many profiles where the links are messed up because they put the complete link where only a username should be put into.

Maybe by appending `username`and `link` to the accompanying labels? I.e. `Twitter username:`, `Reddit username`, `KSP Forums link` (or `KSP Forums profile link`?) etc.

**Comment by HebaruSan** [comment]
Agreed. How about some client side validation? When the user tries to save, we could inspect the fields and raise an alert if any of them are formatted wrong.

**Comment by DasSkelett** [comment]
Sounds good. We don't need to do a full URL parsing, checking if it begins with `http://`or `https://`is probably enough. Hoping that none of the external sites allow usernames starting with this string.

**Comment by HebaruSan** [comment]
OK, renamed the labels to include either "link" or "username" and added some validation.

- I assumed that usernames on these sites can include alphanumerics plus dash, underscore, or period, but in the errors I just said "alphanumeric" because that level of detail is not needed to tell the user not to paste a URL in there
- I did **not** add validation for the forum field, because it's not actually required for it to be a link; you can enter just your user name and it will display just fine, so it seemed like overkill to raise an error if a user had done that in the past and just wanted to change some other field.

**Review by DasSkelett — APPROVED** [review]
Rebased on alpha after #380 

Looks good!

**Pull request merged**
