### PR TITLE
Run database migrations after pulling changes

### PR DESCRIPTION
**Pull request by HebaruSan**
## Motivation

After #369 was merged, the alpha server was left in a semi-functional state because its alembic migration wasn't executed. This command fixed it (I used the migration id in place of `head`, but I want to document the best version of it):

```
cd /SpaceDock
bin/alembic upgrade head
```

This happens automatically when you run `./start-server.sh`, via `./spacedock database migrate`:

https://github.com/KSP-SpaceDock/SpaceDock/blob/ebb54cb85da0ea798cdbc3578e52b56fd04ee0c2/start-server.sh#L34

... which does this:

https://github.com/KSP-SpaceDock/SpaceDock/blob/ebb54cb85da0ea798cdbc3578e52b56fd04ee0c2/spacedock#L12-L15

https://github.com/KSP-SpaceDock/SpaceDock/blob/ebb54cb85da0ea798cdbc3578e52b56fd04ee0c2/spacedock#L75-L79

## Changes

Now after the web hook pulls changes from GitHub, and before it restarts the sever, it also tries to run the alembic migrations.

### CODE REVIEW

**Comment by HebaruSan** [comment]
Will that work?

**Comment by DasSkelett** [comment]
After all these years! Nice to see this finally happening. Not to say I would've done this years ago, but... I'd have done this years ago.

> Will that work?

Hard to say, testing this code section is a bit hard. I did run a manual
```python
alembic.command.downgrade(alembic.config.Config('alembic.ini'), '426e0b848d77')
alembic.command.upgrade(alembic.config.Config('alembic.ini'), 'head')
```
which worked just fine (except one unrelated issue, see below). I don't see why it wouldn't in the celery task.

Also while running this on a new table, I realized that the new primary key of `mod_followers` from #369 isn't called `pk_mod_followers` but `mod_followers_pkey` if generated from scratch instead of the migration. This made the downgrade fail.
Appending `name='pk_mod_followers'` to the `PrimaryKeyConstraint` declaration should fix that.

Not a huge bug, it's unlikely that someone downgrades newly created databases except for testing, but it's nice to have things consistent. Do you want to add this to this PR, since we're already in the area of db migrations?

**Comment by HebaruSan** [comment]
Good catch, fixed.

**Comment by DasSkelett** [comment]
Found some more bugs while testing #357 and related to #369, but put them in my own separate [PR](https://github.com/KSP-SpaceDock/SpaceDock/pull/379), since they touch more code now that doesn't have anything to do with this PR.

**Review by DasSkelett — APPROVED** [review]
We'll only find out whether it works once we try it out on alpha, so let's give it a go.

**Comment by DasSkelett** [comment]
As far as I can tell it worked perfectly after merging #374:
```
$ sudo -u www-data bin/alembic current
833ba1ee8c72 (head)
```

**Pull request merged**
