### PR TITLE
[proposal] Remove addresses from "To" field, BCC instead + add Precedence header

### LINKED ISSUE #41: Gmail doesn't seemed to be receiving confirmation emails
After almost 3-4 hours since I registered, no emails have been received. Not sure if Google is just blocking emails or if it is just the mail system being slow.

### LINKED ISSUE #68: Remove recipient list from "To" field in mod update emails
The recipients should be BCC (blind copied), rather than all listed in the "To" field for the mod update emails. Potential privacy issue.

### PR DESCRIPTION
**Pull request by NecroBones**
Closing privacy issue by hiding the "To" field altogether. Just commented out the "To" line. For issue #68 . Not tested.

Fixes #41, Fixes #68

### CODE REVIEW

**Comment by EIREXE** [comment]
I'll merge once i test it.

**Comment by NecroBones** [comment]
Added code to also address #41, and add a conditional for #68.

**Comment by FrikFry** [comment]
@EIREXE @NecroBones Have either of you tested this?

**Comment by NecroBones** [comment]
I have not. I still don't have a copy of the project set up and running locally. Just haven't had the time to investigate.

**Comment by FrikFry** [comment]
I fiddled with this on my local server and it seems to work. I leave it as an exercise for @godarklight on whether to merge this into master and then dev or the other way around.

**Pull request merged**
