### PR TITLE
Add game ID filter

### LINKED ISSUE #465: Ability to filter results on API for a specific game
Description (What went wrong?):

I'm working on the installer for SpaceWarp over at https://github.com/SpaceWarpDev/Space-Warp-Installer and https://github.com/RedstoneWizard08/Space-Warp-Installer and I'm trying to filter mods on the API for only KSP2, but there is no option for that, and then the pagination breaks because it fetches all mods and some pages will be blank.

Reproduction Steps (What did you do?):

```ts
import axios from "axios";

import { finishBrowseResult } from "./models/browse";
import { finishFullModInfo } from "./models/modinfo/full";

export class SpaceDockAPI {
    private base: string;

    public constructor(baseUrl?: string) {
        this.base = baseUrl || SpaceDockAPI.getDefaultAPIUrl();
    }

    public static getDefaultAPIUrl() {
        return "https://spacedock.info/api";
    }

    public async getMods() {
        const response = await axios.get(`${this.base}/browse`);
        
        return finishBrowseResult(response.data);
    }

    public async getMod(id: string | number) {
        const response = await axios.get(`${this.base}/mod/${id}`);

        return finishFullModInfo(response.data);
    }

    // example: getModsForGame(22407) = KSP2
    public async getModsForGame(gameId: number) {
        const response = await this.getMods();
        const mods = response.result.filter((mod) => mod.game_id == gameId);

        return mods;
    }
}
```

Expected Behavior (What do you think should have happened instead?):

What I would like is to be able to filter on the browse API with more parameters like `game_id` and `game_version` to allow for easier use.

Environment (OS/Browser/Plugins/etc):

1. Windows/Wry (Tauri)/Tauri/Preact/TypeScript
2. Chrome OS/Chrome/Preact/Vite/TypeScript
3. Linux (Ubuntu 22.04)/TypeScript

Extra Information (Screenshots/Error Messages/Javascript Console Output):

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Fixes #465

### CODE REVIEW

**Comment by V1TA5** [comment]
This should be available in all sub paths of browse like "New"

**Comment by RedstoneWizard08** [comment]
Okay, I'll fix that too.

**Comment by V1TA5** [comment]
This should be available in all sub paths of browse like "New"

**Comment by V1TA5** [comment]
Thank you :)

**Comment by HebaruSan** [comment]
Now that we're looking at this closely, I strongly suspect these old lines don't do anything (and therefore the `order` and `orderby` params are broken):

https://github.com/KSP-SpaceDock/SpaceDock/blob/dbd67221961376193983028c8977c51b5296204d/KerbalStuff/blueprints/api.py#L325-L328

Just calling `order_by` doesn't change the query, we would need to overwrite the `mods` variable like:

```python
    if order == "desc":
        mods = mods.order_by(desc(orderby))
    else:
        mods = mods.order_by(asc(orderby))
```

Maybe you could confirm this with the client that you're testing. We might as well fix that while we're touching this code.

**Comment by RedstoneWizard08** [comment]
@HebaruSan I think that `/api/browse/new` is the only one that I can implement that for. The other ones don't use the same API that it does, which is directly querying the database.

**Comment by RedstoneWizard08** [comment]
> Now that we're looking at this closely, I strongly suspect these old lines don't do anything (and therefore the `order` and `orderby` params are broken):
> 
> https://github.com/KSP-SpaceDock/SpaceDock/blob/dbd67221961376193983028c8977c51b5296204d/KerbalStuff/blueprints/api.py#L325-L328
> 
> Just calling `order_by` doesn't change the query, we would need to overwrite the `mods` variable like:
> 
> ```python
>     if order == "desc":
>         mods = mods.order_by(desc(orderby))
>     else:
>         mods = mods.order_by(asc(orderby))
> ```
> 
> Maybe you could confirm this with the client that you're testing. We might as well fix that while we're touching this code.

Yeah it doesn't change anything rn. I'll fix that too.

**Comment by V1TA5** [comment]
Your on fire. Tell me when youre satisfied with the state and i should merge it.

**Comment by RedstoneWizard08** [comment]
I'm satisfied rn lol

**Comment by HebaruSan** [comment]
The one remaining comment that I had was that the `game_version` parameter might be clearer as `game_version_id` so the user of the API knows it's not something like "0.1.0.0" but a database number.

Also we forgot to update the docs:

https://github.com/KSP-SpaceDock/SpaceDock/blob/master/api.md#browse

**Comment by HebaruSan** [comment]
@RedstoneWizard08, @V1TA5, I'm going to address the concerns from my previous comment in a new PR (`game_version_id` as the param name, updating the API docs).

Confirmed the sorting fix is working:

- https://alpha.spacedock.info/api/browse?order=asc
- https://alpha.spacedock.info/api/browse?order=desc

And so is the new filter:

- https://alpha.spacedock.info/api/browse?game_id=1
- https://alpha.spacedock.info/api/browse?game_id=2

**Comment by HebaruSan** [comment]
Actually, the API currently doesn't expose the internal game version id at all, so it would not be possible for API users to use that parameter, so we should probably just switch `game_version` to matching `Game.friendly_version`.

**Comment by RedstoneWizard08** [comment]
The version should be, if you query `/API/[game_id]/versions`

**Comment by HebaruSan** [comment]
Ahh, that's fair. I was looking at `/api/browse` itself, where we just get `versions[].game_version` as `GameVersion.friendly_version`:

```json
{"friendly_version":"1.7","game_version":"1.10.0","id":24,"created":"2020-07-28T18:03:39.568092+00:00","download_path":"/mod/5/AwesomeMod/download/1.7","changelog":"","downloads":47}
```

In that case, maybe we should support both.

**Pull request merged**
